### ISSUE TITLE
вопросик по Webpack

### ISSUE THREAD

**Issue by Soluyanov-Andrey** [harryheman/Webpack5-Max#1]
Решил посмотреть данную сборку. Если в index.js вставить следующий код убрав весь react
```
const getRecource = async(url)=>{
    const res = await fetch(url);
    const body = await res.json();
    return body;
};

getRecource('https://swapi.dev/api/people/1/')
    .then((body)=>{
        console.log(body);
    });
```
То в консоли посыпятся ошибки.
```
index.js?2dec:6 Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (index.js?2dec:6)
    at eval (index.js?2dec:35)
    at Object../src/index.js (main.bundle.js:39)
    at __webpack_require__ (main.bundle.js:409)
    at main.bundle.js:1380
```
Если использовать create react app, то этот код работает в их сборки за ура.У самого тоже есть сборка чуть попроще твоей, но присутствует такая же проблема. Есть мысли как это чинить?

**Comment by Soluyanov-Andrey** [comment]
В своей сборке починил взяв отсюда [https://qna.habr.com/q/509040](https://qna.habr.com/q/509040).

При работе с webpack решил данную проблему так
установил - babel-polyfill

`npm i --save-dev babel-polyfill`

в конфиге вебпака
```
require('babel-polyfill');
module.exports = {
  // BASE config
  externals: {
    paths: PATHS
  },
  entry: {
    app: ['babel-polyfill', PATHS.src]
  }, ..
```

**Comment by harryheman** [comment]
Во-первых, спасибо за вопрос. Во-вторых, нашел другое решение: https://babeljs.io/docs/en/babel-plugin-transform-runtime
